# -- (Optional) When using a custom network
networks:
  frontend:
    external: true
services:
  twingate_ness01:
    container_name: twingate_ness01
    image: twingate/connector:latest
    environment:
      - TWINGATE_NETWORK=networkwelp
      - TWINGATE_ACCESS_TOKEN=eyJhbGciOiJFUzI1NiIsImtpZCI6IndONEYtNnhwNzRjODdwSDNpRnhmQmV4a2oySzRPUk9sdkZoNjJzdVdaSWMiLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiMTYzNzkxIiwiZGlkIjoiOTY5NjI5IiwianRpIjoiZDQ1NmRkMjAtMDRiNy00ZDAxLThjMzktYTZjNTc0MmMxM2FlIiwiaXNzIjoidHdpbmdhdGUiLCJhdWQiOiJuZXR3b3Jrd2VscCIsImV4cCI6MTY5NjQ1NzE2OSwiaWF0IjoxNjk2NDUzNTY5LCJ2ZXIiOiI0IiwidGlkIjoiNTU0NTUiLCJybnciOjE2OTY0NTM4NjksInJuZXRpZCI6IjY5MDkxIn0.NrzaBN-dn-A8dzw52Au-Pa6od4tByupH78qTDYR13RUWEV4ENkhzJqSRD537FvOxV17sdMV5fCvcgLtnFOsitA
      - TWINGATE_REFRESH_TOKEN=ZkrKVML2j8xuRZcf72RuFZ7NPBmgTgs4RJdNtnLEs02T8xOfomeWCGqZpsLLk3qAu7UiWsAeg_THKRsHhEQcywqZPBr8li9FxNV7NOSL3A9-JzlRugxJ3J2mvrVKeQnYf1c6gg
      # -- (Optional) Change loglevel
      # - TWINGATE_LOG_LEVEL=3
      # -- (Optional) Add custom DNS Server
      # - TWINGATE_DNS=192.168.1.34:53
      - TWINGATE_LABEL_HOSTNAME=`hostname`
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    # -- (Optional) When using a custom network
    networks:
       - frontend
    restart: unless-stopped
