version: '3'
services:
  jenkins-blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    restart: always
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /mnt/stockage/jenkins-data:/var/jenkins_home
      - /mnt/stockage/jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:
